Documentation: Update UG
AY2324S1-CS2103T-T17-2/tp pull request #142
Opened 2023-10-31 16:34 UTC by alientian

2023-10-31 17:19 UTC, AlagappanRa approved these changes
LGTM

2023-10-31 17:44 UTC, papataco14 requested changes
Perhaps you can group the images under a edit-command and remark-command folder to avoid cluttering?

2023-10-31 18:19 UTC, GlendaChong requested changes
Could try to follow the current format of diagrams annotations and feature descriptions.

2023-10-31 18:19 UTC, GlendaChong commented on docs/UserGuide.md
> +use the `remark` command to input the additional details.
Description should be in italics. Make it more engaging too

2023-10-31 18:19 UTC, GlendaChong commented on docs/UserGuide.md
> +>`[re/REMARK]` : type prefix `re/` followed by the remark you want to add </br>
Don't use brackets around re/REMARK? I think we will put a note that [] means that the fields are optional, in this case it isn't

2023-10-31 18:19 UTC, GlendaChong commented on docs/UserGuide.md
> +![RemarkDemo2.png](images/RemarkDemo2.png)
Could provide more user-centric description and step-by-step guide.

2023-10-31 18:19 UTC, GlendaChong commented on docs/UserGuide.md
> +use the `unremark` command to delete it.
Similarly, description to be in italics, and more engagement. Use YOU-language LOL

2023-10-31 18:19 UTC, GlendaChong commented on docs/UserGuide.md
> +1.You received a email from Microsoft to interview for a Frontend Developer role which is different from the role you applied for.
received **an** email from .... for a Frontend Developer role **instead**, **which is different from the Software Engineer role you applied for.**

2023-10-31 18:19 UTC, GlendaChong commented on docs/UserGuide.md
> +To edit, type `edit 2 s/PI r/Frontend Developer`
To edit the company's information....

2023-10-31 18:19 UTC, GlendaChong commented on docs/images/RemarkErrorMsg.png
Maybe edit error messages to be similar to what we have now? 
Along the lines of:  
Oops! Remark should not be blank. Please try again!

Can refer to the current code base

2023-10-31 18:19 UTC, GlendaChong commented on docs/images/UnremarkDemo1.png
colours of boxes used is not standardised

green is for success, while red is for failure/errors

2023-11-02 02:32 UTC, GlendaChong approved these changes
Might have to update images after the commands changed

2023-11-02 02:32 UTC, GlendaChong commented on docs/images/edit-command/EditErrMsg.png
If the view of the app is in full screen, I believe we are able to see the entire line of parameters code. 
might just not be able to see the example which is on the 4th line.

2023-11-02 02:32 UTC, GlendaChong commented on docs/UserGuide.md
> +1.received an email from Microsoft to interview for a Frontend Developer role instead, which is different from the Software Engineer role you applied for.
**You** received...

2023-11-02 12:46 UTC, papataco14 approved these changes
LGTM

2023-11-02 12:47 UTC, merged