Update UG bugs
AY2324S1-CS2103T-T17-2/tp pull request #226
Opened 2023-11-05 06:44 UTC by tayruxin

- The hyperlink throughout the UG were fixed
- Quick tour: The images were removed and the stories too to make it less repetitive 
- Navigating the user guide: split up symbols and text and added in the missing header 
- Quick start: hyperlink fixed **however the link to release is not fixed. Will wait till the final release is out to edit**
- GUI interface: Edit the image and add a table to explain what each component does

2023-11-05 19:06 UTC, GlendaChong requested changes

2023-11-05 19:06 UTC, GlendaChong commented on docs/UserGuide.md
> +Allowing you to find, list, filter, and sort companies.
Suggestion: 

[General Features](https://chat.openai.com/#general-features): This section equips you with essential tools to navigate LinkMeIn effectively. Here, you can access help, clear all entries, and gracefully exit LinkMeIn.

[Company Management Features](https://chat.openai.com/#company-management-features): Dive into this section to **engage with individual company entries**. You have the power to add, view, edit, delete companies, and even add your own remarks to companies.

[Company List Features](https://chat.openai.com/#company-list-features): Unlock the potential of this section to **interact with the list of companies**. Explore options to find, list, filter, and sort companies, managing all companies with ease.

2023-11-06 17:16 UTC, GlendaChong approved these changes
LGTM

2023-11-06 17:18 UTC, merged

2023-11-07 17:19 UTC, papataco14 commented
Closes #200