Update UG: Add planned enhancements
AY2324S1-CS2103T-T17-2/tp pull request #278
Opened 2023-11-12 16:35 UTC by alientian

2023-11-12 16:39 UTC, tayruxin requested changes

2023-11-12 16:39 UTC, tayruxin commented on docs/DeveloperGuide.md
> +**How the feature will be changed**
should be **Proposed Enhancement**

2023-11-12 16:39 UTC, tayruxin commented on docs/DeveloperGuide.md
> +Hence, the `remark 1 re/` command is modified to become a way to copy and paste existing remarks so that remarks become cumulative.
Add in a section called **Examples** which include some sample output that the user will see or something

2023-11-13 03:19 UTC, tayruxin approved these changes

2023-11-13 03:55 UTC, GlendaChong requested changes

2023-11-13 03:55 UTC, GlendaChong commented on docs/DeveloperGuide.md
> +**Potential flaw in current implementation**
Pascal case for headers

2023-11-13 03:55 UTC, GlendaChong commented on docs/DeveloperGuide.md
> +Hence, the `remark INDEX re/` command is modified to become a way to copy and paste existing remarks so that remarks become cumulative.
```suggestion
Hence, the `remark INDEX re/` command is modified such that if the user does not enter any remarks after `re/` prefix, the message displayed to the user will include their existing remarks. Should they wish to add on to their existing remarks, they can easily copy their existing remarks from the Message Box.
```

2023-11-13 03:55 UTC, GlendaChong commented on docs/DeveloperGuide.md
> +When `remark 1 re/` is entered, the Message Box will display as shown below.
```suggestion
When `remark 1 re/` is entered, the Message Box will be displayed as shown below.
```

2023-11-13 03:55 UTC, GlendaChong commented on docs/DeveloperGuide.md
> +The user can copy from the Message Box and add on his remark. A sample input is
```suggestion
The user can copy from the Message Box and add on to his remarks. A sample input of an updated remark will then be: 
```

2023-11-13 03:55 UTC, GlendaChong commented on docs/DeveloperGuide.md
> +`remark 1 re/Require experience in Java, Interview on 12/12/2023, Interview went well!`
will the success message remain the same? probably specify at the top

2023-11-13 05:17 UTC, GlendaChong approved these changes
lgtm

2023-11-13 05:17 UTC, merged