View function
AY2324S1-CS2103T-T17-2/tp pull request #85
Opened 2023-10-16 06:06 UTC by tayruxin

2023-10-16 15:27 UTC, GlendaChong requested changes

2023-10-16 15:27 UTC, GlendaChong commented on src/main/java/seedu/address/logic/commands/ViewCommand.java
> +     * @param targetIndex index of the company in the filtered company list to view
I think there should be a space between description and @params. Missing full stops too.

2023-10-16 15:27 UTC, GlendaChong commented on src/main/java/seedu/address/logic/commands/ViewCommand.java
> +        // instanceof handles nulls
Do you mean null cases instead of nulls?

2023-10-16 16:22 UTC, tayruxin commented on src/main/java/seedu/address/logic/commands/ViewCommand.java
> + * Deletes a company identified using it's displayed index from the address book.
Resolved

2023-10-17 02:54 UTC, GlendaChong approved these changes
Generally LGTM, though there's still some minor styling issues to be fixed

2023-10-17 02:54 UTC, GlendaChong commented on src/main/java/seedu/address/logic/commands/ViewCommand.java
> +     * Creates an ViewCommand to view the specified {@code Company}.
Creates "a" ViewCommand...

2023-10-17 02:54 UTC, GlendaChong commented on src/main/java/seedu/address/logic/commands/ViewCommand.java
> +     * @param targetIndex index of the company in the filtered company list to view
According to the [Javadocs standards](https://se-education.org/guides/conventions/java/intermediate.html#comments), there should be punctuations behind each parameter description.

2023-10-17 02:54 UTC, GlendaChong commented on src/main/java/seedu/address/logic/parser/ViewCommandParser.java
> +     * @throws ParseException if the user input does not conform the expected format
Likewise, missing full stop here too

2023-10-17 02:55 UTC, merged